spring:
  datasource:
    url: jdbc:h2:mem:taskdb_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

server:
  port: 8105

app:
  jwt:
    secret: c25WTkRldk9ubHlUaGlzS2V5TXVzdEJlMzJCeXRlc0xvbmcxMjM0NTY=
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: WARN
    snvn.taskmanagementservice: DEBUG
    org.springframework.test: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

