spring:
  application:
    name: splunk-service

# Server Configuration
server:
  port: 8104

# Splunk HEC Configuration
splunk:
  hec:
    url: https://localhost:8088/services/collector
    token: a22e99ae-51de-4bff-8567-a726b83760d6
    index: main
    source: splunk-service
    sourcetype: _json
    enabled: true
    batch-size: 100
    flush-interval: 5000
    ssl-verify: false


# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

## Logging Configuration
#logging:
#  level:
#    root: INFO
#    snvn.splunkservice: DEBUG
#  file:
#    name: logs/splunk-service.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

